os:
  - linux

language: php

php:
  - '7.1'
  
before_script:
  - composer self-update
  - composer install
  - cp .env.travis .env
  - phpenv rehash
  
script:
  - vendor/bin/phpunit --coverage-text
  - phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers