language: php

php:
- '7.1'

services:
- mysql

before_script:
- cp .env.travis .env
- mysql -e 'create database unda;'
- mysql -e 'show databases'
- composer self-update
- composer install --no-interaction
- php artisan key:generate
- php artisan migrate
- mysql -e 'show databases;'
- mysql -e 'SELECT * FROM INFORMATION_SCHEMA.TABLES;'
- sudo apt-get update
- sudo apt-get install apache2 libapache2-mod-fastcgi
# enable php-fpm
- sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
- sudo a2enmod rewrite actions fastcgi alias
- echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
- sudo chown -R travis:travis /var/lib/apache2/fastcgi
- ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
# configure apache virtual hosts
- sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/000-default.conf
- sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
- sudo service apache2 restart

script:
    - vendor/bin/phpunit
    - vendor/bin/behat