language: php

php:
- '7.1'

services:
- mysql

before_script:
- cp .env.travis .env
- mysql -e 'create database testing_db;'
- mysql -e 'show databases'
- composer self-update
- composer install --no-interaction
- php artisan key:generate
- php artisan migrate --database='testing_db'

script:
    - vendor/bin/phpunit
    - vendor/bin/behat